model_source: "pytorch_hub"
model_repo: pytorch/vision
model_name: "alexnet"
model_weights: "DEFAULT" # torch.hub weights (not necesssary for cornet models). Leave empty for untrained.
pretrained: True



data_root: categ_images # folder containing four subfolders (animals, faces, objects, places), 20 images each

batch_size: 8           # how many images to process at once

out_dir: unit_selectivity
metrics: [mannwhitneyu, hedgesg]