subdir: "test/"
tasks:
  - function: "categ_corr_lineplot"
    parameters:
      damage_layers: ["V1"]
      activations_layers: ["V1","V2","V4","IT"]
      damage_type: "noise"
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      categories: ["total"]
      verbose: 0
  - function: "categ_corr_lineplot"
    parameters:
      damage_layers: ["V2"]
      activations_layers: ["V1","V2","V4","IT"]
      damage_type: "noise"
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      categories: ["total"]
      verbose: 0
  - function: "categ_corr_lineplot"
    parameters:
      damage_layers: ["V4"]
      activations_layers: ["V1","V2","V4","IT"]
      damage_type: "noise"
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      categories: ["total"]
      verbose: 0
  - function: "categ_corr_lineplot"
    parameters:
      damage_layers: ["IT"]
      activations_layers: ["V1","V2","V4","IT"]
      damage_type: "noise"
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      categories: ["total"]
      verbose: 0
  - function: "categ_corr_lineplot"
    parameters:
      damage_layers: ["V1","V2","IT"]
      activations_layers: ["V2","IT"]
      damage_type: "noise"
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      categories: ["total"]
      verbose: 0
