subdir: "vgg16_c/"
tasks:
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/vgg16_c/"
      damage_layers: ["block1"]
      activations_layers: ["features_30"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-15,105]
      data_type: "selectivity"
      selectivity_fraction: 0.01
      selection_mode: percentage
      model_tag: vgg16
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/vgg16_c/"
      damage_layers: ["block1"]
      activations_layers: ["features_30"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-15,105]
      data_type: "selectivity"
      selectivity_fraction: 0.01
      selection_mode: percentage
      model_tag: vgg16
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/vgg16_c/"
      damage_layers: ["block1"]
      activations_layers: ["features_30"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.1,1]
      data_type: "selectivity"
      selectivity_fraction: 0.01
      selection_mode: percentage
      model_tag: vgg16
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/vgg16_c/"
      damage_layers: ["block1"]
      activations_layers: ["features_30"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.1,1]
      data_type: "selectivity"
      selectivity_fraction: 0.01
      selection_mode: percentage
      model_tag: vgg16


  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/vgg16_c/"
      damage_layers: ["block2"]
      activations_layers: ["features_30"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-15,105]
      data_type: "selectivity"
      selectivity_fraction: 0.01
      selection_mode: percentage
      model_tag: vgg16
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/vgg16_c/"
      damage_layers: ["block2"]
      activations_layers: ["features_30"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-15,105]
      data_type: "selectivity"
      selectivity_fraction: 0.01
      selection_mode: percentage
      model_tag: vgg16
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/vgg16_c/"
      damage_layers: ["block2"]
      activations_layers: ["features_30"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.1,1]
      data_type: "selectivity"
      selectivity_fraction: 0.01
      selection_mode: percentage
      model_tag: vgg16
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/vgg16_c/"
      damage_layers: ["block2"]
      activations_layers: ["features_30"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.1,1]
      data_type: "selectivity"
      selectivity_fraction: 0.01
      selection_mode: percentage
      model_tag: vgg16


  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/vgg16_c/"
      damage_layers: ["block3"]
      activations_layers: ["features_30"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-15,105]
      data_type: "selectivity"
      selectivity_fraction: 0.01
      selection_mode: percentage
      model_tag: vgg16
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/vgg16_c/"
      damage_layers: ["block3"]
      activations_layers: ["features_30"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-15,105]
      data_type: "selectivity"
      selectivity_fraction: 0.01
      selection_mode: percentage
      model_tag: vgg16
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/vgg16_c/"
      damage_layers: ["block3"]
      activations_layers: ["features_30"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.1,1]
      data_type: "selectivity"
      selectivity_fraction: 0.01
      selection_mode: percentage
      model_tag: vgg16
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/vgg16_c/"
      damage_layers: ["block3"]
      activations_layers: ["features_30"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.1,1]
      data_type: "selectivity"
      selectivity_fraction: 0.01
      selection_mode: percentage
      model_tag: vgg16


  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/vgg16_c/"
      damage_layers: ["block4"]
      activations_layers: ["features_30"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-15,105]
      data_type: "selectivity"
      selectivity_fraction: 0.01
      selection_mode: percentage
      model_tag: vgg16
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/vgg16_c/"
      damage_layers: ["block4"]
      activations_layers: ["features_30"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-15,105]
      data_type: "selectivity"
      selectivity_fraction: 0.01
      selection_mode: percentage
      model_tag: vgg16
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/vgg16_c/"
      damage_layers: ["block4"]
      activations_layers: ["features_30"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.1,1]
      data_type: "selectivity"
      selectivity_fraction: 0.01
      selection_mode: percentage
      model_tag: vgg16
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/vgg16_c/"
      damage_layers: ["block4"]
      activations_layers: ["features_30"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.1,1]
      data_type: "selectivity"
      selectivity_fraction: 0.01
      selection_mode: percentage
      model_tag: vgg16


  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/vgg16_c/"
      damage_layers: ["block5"]
      activations_layers: ["features_30"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-15,105]
      data_type: "selectivity"
      selectivity_fraction: 0.01
      selection_mode: percentage
      model_tag: vgg16
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/vgg16_c/"
      damage_layers: ["block5"]
      activations_layers: ["features_30"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-15,105]
      data_type: "selectivity"
      selectivity_fraction: 0.01
      selection_mode: percentage
      model_tag: vgg16
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/vgg16_c/"
      damage_layers: ["block5"]
      activations_layers: ["features_30"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.1,1]
      data_type: "selectivity"
      selectivity_fraction: 0.01
      selection_mode: percentage
      model_tag: vgg16
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/vgg16_c/"
      damage_layers: ["block5"]
      activations_layers: ["features_30"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.1,1]
      data_type: "selectivity"
      selectivity_fraction: 0.01
      selection_mode: percentage
      model_tag: vgg16


  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/vgg16_c/"
      damage_layers: ["block1","block2","block3","block4","block5"]
      activations_layers: ["features_30"]
      damage_type: "connections"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.05,0.25]
      data_type: "selectivity"
      selectivity_fraction: 0.01
      selection_mode: percentage
      model_tag: vgg16
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/vgg16_c/"
      damage_layers: ["block1","block2","block3","block4","block5"]
      activations_layers: ["features_30"]
      damage_type: "noise"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.05,0.25]
      data_type: "selectivity"
      selectivity_fraction: 0.01
      selection_mode: percentage
      model_tag: vgg16
