subdir: "cornet_rt5_c/"
tasks:
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_all/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "eccentricity_0.80-1.00"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      data_type: "selectivity"
      flip_x_axis: False
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 1
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_all/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "eccentricity_0.80-1.00"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      data_type: "selectivity"
      flip_x_axis: False
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 1
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_all/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "eccentricity_0.60-1.00"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      data_type: "selectivity"
      flip_x_axis: False
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 1
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_all/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "eccentricity_0.60-1.00"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      data_type: "selectivity"
      flip_x_axis: False
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 1
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_all/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "eccentricity_0.30-1.00"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      data_type: "selectivity"
      flip_x_axis: False
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 1
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_all/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "eccentricity_0.30-1.00"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      data_type: "selectivity"
      flip_x_axis: False
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 1