subdir: "cornet_rt5_c/"
tasks:
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.05,1.05]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V2"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.05,1.05]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V4"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.05,1.05]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["IT"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.05,1.05]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage

  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.05,1.05]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V2"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.05,1.05]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V4"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.05,1.05]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["IT"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.05,1.05]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage

  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c+b/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "units"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.05,1.05]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c+b/"
      damage_layers: ["V2"]
      activations_layers: ["IT"]
      damage_type: "units"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.05,1.05]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c+b/"
      damage_layers: ["V4"]
      activations_layers: ["IT"]
      damage_type: "units"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.05,1.05]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c+b/"
      damage_layers: ["IT"]
      activations_layers: ["IT"]
      damage_type: "units"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.05,1.05]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage

  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c+b/"
      damage_layers: [V1,V2,V4,IT]
      activations_layers: ["IT"]
      damage_type: "units"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.05,0.4]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: [V1,V2,V4,IT]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.05,0.4]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: [V1,V2,V4,IT]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.05,0.4]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: [V1,V2,V4,IT]
      activations_layers: ["IT"]
      damage_type: "unit_activations"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.05,0.4]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage

  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.05,1.05]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.05
      selection_mode: percentage

  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.05,1.05]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.1
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.05,1.05]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.5
      selection_mode: percentage

  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-5,105]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V2"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-5,105]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V4"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-5,105]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["IT"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-5,105]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage

  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-5,105]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V2"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-5,105]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V4"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-5,105]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["IT"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-5,105]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage

  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c+b/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "units"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-5,105]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c+b/"
      damage_layers: ["V2"]
      activations_layers: ["IT"]
      damage_type: "units"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-5,105]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c+b/"
      damage_layers: ["V4"]
      activations_layers: ["IT"]
      damage_type: "units"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-5,105]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c+b/"
      damage_layers: ["IT"]
      activations_layers: ["IT"]
      damage_type: "units"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-5,105]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage

  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c+b/"
      damage_layers: [V1,V2,V4,IT]
      activations_layers: ["IT"]
      damage_type: "units"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-5,105]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: [V1,V2,V4,IT]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-5,105]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: [V1,V2,V4,IT]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-5,105]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: [V1,V2,V4,IT]
      activations_layers: ["IT"]
      damage_type: "unit_activations"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-5,105]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
      selection_mode: percentage

  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-5,105]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.05
      selection_mode: percentage

  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-5,105]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.1
      selection_mode: percentage
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-5,105]
      data_type: "selectivity"
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.5
      selection_mode: percentage