image_dir: "stimuli"
layer_name: "IT"
layer_path: "module._modules.IT._modules.output"
n_bootstrap: 10000
model_source: "cornet"
model_repo: "-"
model_name: "cornet_rt"
model_weights: "" # torch.hub weights (not necesssary for cornet models). Leave empty for untrained.
pretrained: True
vmax: 0.9
mc_permutations: 10 # How many monte carlo permutations on damage to perform

layer_paths_to_damage: 
  - "module._modules.IT"
apply_to_all_layers: True

# Masking damage parameters
manipulation_method: "masking"
masking_level: "connections"  # "connections" or "units"
fraction_to_mask: # Start, N (int), interval [start,N*interval]
  - 0.05
  - 2
  - 0.05

# Noise damage parameters
noise_levels: # Start, N (int), interval [start, N*interval]
  - 0.1
  - 2
  - 0.1
