image_dir: "stimuli"
layer_name: "IT"
layer_path: "module._modules.IT._modules.output"
n_bootstrap: 10000
model_source: "cornet"
model_repo: "-"
model_name: "cornet_rt"
model_weights: "" # torch.hub weights (not necesssary for cornet models). Leave empty for untrained.
pretrained: True
vmax: 0.9

# Damage parameters
manipulation_method: "masking"
masking_level: "units"  # "connections" or "units"
fraction_to_mask:
  - 0.1
  - 0.2
  - 0.3
  - 0.5
layer_paths_to_mask:
  - "module._modules.IT"
apply_to_all_layers: True