image_dir: "stimuli"
layer_name: "V4"
layer_path: "module._modules.V4._modules.output"
n_bootstrap: 10000
model_source: "cornet"
model_repo: "-"
model_name: "cornet_rt"
model_weights: "" # torch.hub weights (not necesssary for cornet models). Leave empty for untrained.
pretrained: True
vmax: 0.4