tasks:
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_z/"
      layers: ["V1","V2","V4","IT"]
      damage_type: "noise"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_z/"
      layers: ["V1","V2","V4","IT"]
      damage_type: "connections"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt/"
      layers: ["V1","V2","V4","IT"]
      damage_type: "noise"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt/"
      layers: ["V1","V2","V4","IT"]
      damage_type: "connections"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
  - function: "plot_avg_corr_mat"
    parameters:
      layers: ["V1"]
      damage_type: "connections"
      damage_levels: [0, 0.1, 0.2, 0.4, 0.5, 0.8] # List
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt/"
  - function: "plot_avg_corr_mat"
    parameters:
      layers: ["V1"]
      damage_type: "connections"
      damage_levels: [0, 0.1, 0.2, 0.4, 0.5, 0.8] # List
      main_dir: "data/haupt_stim_activ/damaged/cornet_z/"