image_dir: "stimuli"
layer_name: "layer4-1-conv2"
layer_path: "layer4.1.conv2"
n_bootstrap: 10000
model_source: "pytorch_hub"
model_repo: "pytorch/vision"
model_name: "resnet50"
model_weights: "IMAGENET1K_V2" # torch.hub weights (not necesssary for cornet models). Leave empty for untrained.
pretrained: True
vmax: 0.4