image_dir: "stimuli"
layer_name: "V2"
layer_path: "module._modules.IT._modules.output" #"module._modules.V2._modules.output" READ from IT atm
n_bootstrap: 10000
model_source: "cornet"
model_repo: "-"
model_name: "cornet_rt"
model_weights: "" # torch.hub weights (not necesssary for cornet models). Leave empty for untrained.
pretrained: True
vmax: 0.4
mc_permutations: 200 # How many monte carlo permutations on damage to perform. Use 21 as in Haupt et al., 2024?
model_time_steps: 4 # feedforward

layer_paths_to_damage: 
  - "module._modules.V2"
apply_to_all_layers: False
include_bias: True
only_conv: False

# Masking damage parameters
manipulation_method: "masking"
masking_level: "connections"  # "connections" or "units"
fraction_to_mask: # Start, N (int), interval [start,N*interval]
  - 0
  - 21
  - 0.05

# Noise damage parameters
noise_levels: # Start, N (int), interval [start, N*interval]
  - 0
  - 51
  - 0.005
